language: ruby
rvm:
  - 1.8.7
  - 1.9.2
  - ree
script: "rake spec"
env:
  - PUPPET_VERSION=2.6.12
  - PUPPET_VERSION=2.7.6
  - PUPPET_VERSION=2.7.10
matrix:
  exclude:
    - rvm: 1.9.2
      env: PUPPET_VERSION=2.6.12
